name: Continuous Integration
on:
  - pull_request
  - push
jobs:
  testing:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - "8.3"
          - "8.4"
          - "8.5"
        mongo:
          - "7.0"
          - "8.0"
    services:
      mongodb:
        image: mongo:${{ matrix.mongo }}
        ports:
          - "27017:27017"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mongodb-mongodb/mongo-php-driver@1.20.1

      - name: Composer
        uses: ramsey/composer-install@v2

      - name: Run Code Standards
        run: vendor/bin/phpcs

      - name: Run Tests
        env:
          DB_HOST: 127.0.0.1
        run: vendor/bin/phpunit

      - name: Report Coverage
        run: CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }} bash <(curl -Ls https://coverage.codacy.com/get.sh) report
